### ISSUE TITLE
ToDos innerhalb des Textes erstellen

### ISSUE THREAD

**Issue by georgbuechner** [kava-i/bebarengan-sepur#1]
@ShadowItaly den bestehenden Text durchlesen, um auf den aktuellen Stand zu kommen und an allen Stellen, an denen (Noch einzufügen o.ä. steht, entsprechende Hinweise als Latex "ToDo" einfügen)

**Comment by alleonhardt** [comment]
Habe die PDF kompiliert sieht sehr gut aus bei mir! Es fehlt nur noch ein Literaturindex, diesen habe ich hinzugefuegt. Er liegt in build/literatur.bib hier muesstest du noch die Daten vom Hegel Buch eintragen welches du verwendest zum zitieren. Ich habe ein paar Rechtschreibfehler verbessert und alles mal durchgelesen. Ein paar Sachen eischeinen mir beim ersten Mal noch etwas schwer verstaendlich ich lese aber nochmal drueber und schreibe das dann als todos. Eine Ubersicht mit den Anderungen kannst du hier sehen: https://github.com/kava-i/bebarengan-sepur/commit/cf100e14e25371d4a7f97c9b3419746e543ae204?diff=split
